[colors.bright]
black = "#a6896b"
red = "#5F4149"
green = "#EB3247"
yellow = "#BC4349"
blue = "#F35645"
magenta = "#F6A73B"
cyan = "#FAD32F"
white = "#eec49a"

[colors.cursor]
cursor = "#eec49a"
text = "#0a1124"

[colors.normal]
black = "#0a1124"
red = "#5F4149"
green = "#EB3247"
yellow = "#BC4349"
blue = "#F35645"
magenta = "#F6A73B"
cyan = "#FAD32F"
white = "#eec49a"

[colors.primary]
background = "#0a1124"
foreground = "#eec49a"
