[colors.bright]
black = "#373b41"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#282a2e"
blue = "#5f819d"
cyan = "#5e8d87"
green = "#8c9440"
magenta = "#85678f"
red = "#a54242"
white = "#707880"
yellow = "#de935f"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.selection]
background = "#4c4c4c"
text = "CellForeground"
