-- Basic config
require("alex.core.keymaps")
require("alex.core.plugins")
require("alex.core.settings")

-- Plugins config
require("alex.plugins.colorscheme")
require("alex.plugins.nvim-tree")
require("alex.plugins.telescope")
require("alex.plugins.trouble")
require("alex.plugins.comments")
require("alex.plugins.bufferline")
require("alex.plugins.lualine")
require("alex.plugins.which-key")
require("alex.plugins.treesitter")
require("alex.plugins.alpha")
require("alex.plugins.auto-session")
require("alex.plugins.autopairs")
require("alex.plugins.colorizer")
-- require("alex.plugins.indent-blankline")
require("alex.plugins.vim-maximizer")
require("alex.plugins.surround")
require("alex.plugins.substitute")
require("alex.plugins.todo-comments")
require("alex.plugins.lazygit")
require("alex.plugins.gitsigns")
require("alex.plugins.lsp.mason")
require("alex.plugins.lsp.lspconfig")
require("alex.plugins.formatting")
require("alex.plugins.linting")
require("alex.plugins.nvim-cmp")
require("alex.plugins.toggleterm")
