[flavor]
# dark = "ayu-dark"
# dark = "catppuccin-frappe"
# dark = "catppuccin-macchiato"
# dark = "catppuccin-mocha"
# dark = "everforest-medium"
# dark = "gruvbox-dark"
# dark = "kanagawa-dragon"
# dark = "kanagawa"
# dark = "nord"
# dark = "onedark"
# dark = "rose-pine-moon"
# dark = "rose-pine"
# dark = "tokyo-night"
# dark = "tokyonight-moon"
# dark = "tokyonight-storm"
# dark = "vscode-dark-modern"
# dark = "vscode-dark-plus"
dark = "my-blue"
