# introduce new language server
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100
feature_words = true                # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[[language]]
name = "git-commit"
language-servers = ["scls"]

# introduce a new language to enable completion on any doc
# by forcing set language with :set-language stub
[[language]]
name = "stub"
scope = "text.stub"
file-types = ["txt", "config", "conf", "kv", "spec"]
# file-types = ["txt", "toml", "config"]
shebangs = []
roots = []
auto-format = false
language-servers = ["scls"]

# python
[[language]]
name = "python"
# append language server to existed languages
language-servers = ["scls", "ruff", "pyright", "pyright-langserver"]
auto-format = false

[language-server.ruff]
command = "ruff"
args = ["server"]

# fish
[[language]]
name = "fish"
language-servers = ["scls", "fish-lsp"]
formatter = { command = "fish_indent" }
auto-format = false

[language-server.fish-lsp]
command = "fish-lsp"
args = ["start"]   

# # lua
# [[language]]
# name = "lua"
# language-servers = [ "scls", "lua-language-server" ]
# roots = [ ".luarc.json", ".luacheckrc", ".stylua.toml", ".git" ]   

[[language]]
name = "lua"
scope = "source.lua"
file-types = ["lua", "rockspec"]
shebangs = ["lua", "luajit"]
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
comment-token = "--"
indent = { tab-width = 2, unit = "  " }
language-servers = ["scls", "lua-language-server"]
# auto-format = false

[language-server.lua-language-server]
command = "lua-language-server"

[language-server.lua-language-server.config.Lua.hint]
enable = true
arrayIndex = "Enable"
paramName = "All"
paramType = true   

# bash
[[language]]
name = "bash"
language-servers = ["scls", "bash-lsp"]

[language-server.bash-lsp]
command = "bash-language-server"
args = ["start"]

# # plain text files
# [[language]]
# name = "markdown"
# language-servers = ["buffer-language-server"]   

# [[language]]
# name = "toml"
# language-servers = ["buffer-language-server"]
